### PR TITLE
Update Noble

### PR DESCRIPTION
**Pull request by dnicolson**
This includes https://github.com/abandonware/noble/pull/327 and https://github.com/abandonware/noble/pull/328.

### CODE REVIEW

**Comment by Apollon77** [comment]
Thank you, honestly I would more love to switch to https://github.com/stoprocent/noble/ fork because more uptodate, prebuild works again and several enhancbements for UART based ble devices ... ok, your typing change would be needed to add there. Could I ask you to do that please as PR? I will then support to get it merged

**Comment by Apollon77** [comment]
Awesome, thank you!

**Comment by Apollon77** [comment]
@dnicolson Did you had a chance to test and verify it still works? If yes I would release it tomorrow, else next week because I'm out some days

**Comment by dnicolson** [comment]
@Apollon77 I haven't been able to test it. I'm only really sure about the initial change, to be honest.

**Comment by Apollon77** [comment]
All right. I release next week

**Comment by Apollon77** [comment]
I merged manually and included your updates, thank you!

**Pull request closed without merging**
